name: An example of an automatic testing action
on:
  push:
    branches:
      - cicd-pipeline
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd app
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cd app
          pytest


